version: '3'
services:
  php7:
    image: dopsy_php7
    container_name: dopsy
    ports:
      - 80:80
    volumes:
      - ./docker/conf/supervisor/conf.d/supervisor.conf:/etc/supervisor/conf.d/supervisor.conf
      - ./docker/conf/nginx/sites-enabled/dopsy.conf:/etc/nginx/sites-enabled/dopsy.conf
      - ./docker/conf/logs:/var/www/logs
      - ./src:/var/www/html

  mysql:
    image: mysql:5.7
    volumes:
      - ./docker/etc/mysql/lib:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root